#cloud-config
users:
  - name: web
    primary_group: web
    groups: wheel
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMviG3oSU/kMfRb0HwJ2dhqU1OC3250ZTD7rPzxYumQb acit4640week3labkey

packages:
  - nginx
  - nmap  